name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        test-suite: [renderer, electron, lint]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run renderer tests
      if: matrix.test-suite == 'renderer'
      run: npm run test:renderer
      
    - name: Run electron tests
      if: matrix.test-suite == 'electron'
      run: npm run test:electron
      
    - name: Run lint
      if: matrix.test-suite == 'lint'
      run: npm run lint
